<!-- BEGIN .content -->
			<div class="content">
				
				<!-- BEGIN .wrapper -->
				<div class="wrapper">
				<b>EN MEMORIA A UN GRAN AMIGO  MAURO TRIVEÑO CHACÓN</b>
				<div>
					                     PARA MI, ES UN HONOR RENDIR  ESTA BREVE MEMORIA A UN GRAN AMIGO SENSIBLE Y CONSEJERO, CON UNA SÓLIDA FORMACIÓN RELIGIOSA. EXCELENTE PADRE, ESPOSO IDEAL Y BUEN CIUDADANO. SUS BUENOS CONSEJOS EN MUCHOS DE NOSOTROS TRASCENDIÓ POSITIVAMENTE Y CONTRIBUYÓ CON SUS ENSEÑANZAS DE LOS PRINCIPIOS Y VALORES,  DEJÁNDONOS COMO LEGADO EL RECONOCIMIENTO Y ABSOLUTO RESPETO A DIOS JEHOVÁ, CONSIDERACIÓN Y RESPETO AL PRÓXIMO Y DEDICACIÓN AL TRABAJO CON HONRADEZ Y RESPONSABILIDAD. IMPULSOR  Y PRIMER MIEMBRO DE LA CONGREGACIÓN DE LOS TESTIGOS DE JEHOVÁ EN LA CUIDAD DE ABANCAY.<br><br>
					                     MAURO TRIVEÑO CHACÓN, NACIDO EN LA CIUDAD DE ABANCAY, EL 15 DE AGOSTO DE 1926. F. 26 – 10 – 1995.  SE INICIÓ  COMO EJECUTIVO EN LOS HOTELES DE TURISTAS DE AREQUIPA, LUEGO EN EL GRAN HOTEL BOLÍVAR Y EN EL HOTEL CRILLÓN DE LIMA.<br><br>
					                     •	SOCIO FUNDADOR DEL CLUB APURÍMAC EN LA CIUDAD DE LIMA.<br>
									•	SOCIO FUNDADOR DE COMERCIAL APURÍMAC S. A. IMPORTADORES  DE ARTÍCULOS ELECTRODOMÉSTICOS Y VEHÍCULOS MOTORIZADOS.<br>
									•	SOCIO FUNDADOR DE LA CÁMARA DE COMERCIO DE APURÍMAC.<br>
									•	PIONERO EN EL TRASPORTE FRIGORÍFICO Y VENTA DE PESCADO EN ABANCAY<br>
									•	EMPRESARIO PROPIETARIO DE LA ZAPATERÍA “MAUTRI “<br>
									•	PROPIETARIO DE LA EX HACIENDA SAHUINTO, PRODUCTORES DE GANADO VACUNO Y CAPRINO. PRODUCTOS FRUTÍCOLAS Y DE FORRAJES.<br>
									•	INDUSTRIAL, FABRICANTE DE DIFERENTES TIPOS DE SOGAS INDUSTRIALES DE CABUYA.<br>
									•	GERENTE GENERAL DE “MERCANTIL MAUTRI “.<br>
									                             CASADO CON LA SRA. MARÍA ALEJANDRINA LEÓN HOYOS DE TRIVEÑO, HIJOS DORIS, ABEL Y KEYLA TRIVEÑO LEÓN.
               <br>MI RECONOCIMIENTO CARIÑOSAMENTE A MAUTRI, AL QUIEN FUE, UN EJEMPLO DE RESPETO Y TRABAJO EN LA CIUDAD DE ABANCAY.    ALFONSO GAMARRA C.      


				</div>

					<div class="article-image">
						<span class="image-border"><img src="<?php echo base_url(); ?>assets/images/photos/image-21.jpg" alt="" title="" /></span>
					</div>
					

					
				<!-- END .wrapper -->
				</div>
				
			<!-- BEGIN .content -->
			</div>